apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "namespace_rm.fullname" . }}
  labels:
    {{- include "namespace_rm.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["namespaces","pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["delete"]
